name: Push (main)

on:
  push:
    branches:
      - main
    paths:
      - "rockcraft.yaml"
      - "files/**"
      - ".github/workflows/**.yaml"

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        run: |
          sudo snap install docker
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker

      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo

      - name: Install yq
        run: |
          sudo snap install yq

      - uses: actions/download-artifact@v3
        with:
          name: seldon-core-operator-rock

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Import and push to Docker Hub
        run: |
          version="$(cat rockcraft.yaml | yq e '.version')"

          sudo skopeo \
            --insecure-policy \
            copy \
            oci-archive:"seldon-core-operator_${version}_amd64.rock" \
            docker-daemon:"jnsgruk/seldon-core-operator:${version}"

          docker push "jnsgruk/seldon-core-operator:${version}"
