# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 12 * * *"

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.240.5
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
